---
- name: Ensure MariaDB packages are installed.
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - mariadb
    - mariadb-server
    - mariadb-libs
    - MySQL-python
    - perl-DBD-MySQL

- name: Copy my.cnf global MariaDB configuration.
  template:
    src: my.cnf.j2
    dest: "/etc/my.cnf"
    owner: root
    group: root
    mode: 0644
    force: "{{ overwrite_global_mycnf }}"
  notify: restart mariadb

- name: Verify MariaDB include directory exists.
  file:
    path: "/etc/my.cnf.d"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: mariadb_config_include_files | length

- name: Copy my.cnf override files into include directory.
  template:
    src: "{{ item.src }}"
    dest: "/etc/my.cnf.d/{{ item.src | basename }}"
    owner: root
    group: root
    mode: 0644
    force: "{{ item.force | default(False) }}"
  with_items: "{{ mariadb_config_include_files }}"
  notify: restart mariadb

- name: Create slow query log file (if configured).
  shell: "touch {{ mariadb_slow_query_log_file }} creates={{ mariadb_slow_query_log_file }}"
  when: mariadb_slow_query_log_enabled

- name: Create datadir if it does not exist
  file:
    path: "{{ mariadb_datadir }}"
    state: directory
    owner: mysql
    group: mysql
    mode:  0755
    setype: mysqld_db_t

- name: Set ownership on slow query log file (if configured).
  file:
    path: "{{ mariadb_slow_query_log_file }}"
    state: file
    owner: mysql
    group: mysql
    mode: 0640
  when: mariadb_slow_query_log_enabled

- name: Create error log file (if configured).
  shell: "touch {{ mariadb_log_error }} creates={{ mariadb_log_error }}"
  when: mariadb_log == "" and mariadb_log_error != ""

- name: Set ownership on error log file (if configured).
  file:
    path: "{{ mariadb_log_error }}"
    state: file
    owner: mysql
    group: mysql
    mode: 0640
  when: mariadb_log == "" and mariadb_log_error != ""

- name: Ensure MariaDB is started and enabled on boot.
  service: "name=mariadb state=started enabled={{ mariadb_enabled_on_startup }}"
  register: mariadb_service_configuration

- include: secure.yml
  static: no

- include: custom.yml
  static: no