---
- name: Disallow root login remotely
  command: 'mysql -NBe "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: false

- name: Get list of hosts for the root user.
  command: mysql -NBe 'SELECT Host FROM mysql.user WHERE User = "root" ORDER BY (Host="localhost") ASC'
  register: mariadb_root_hosts
  changed_when: false
  check_mode: no

- name: Update MariaDB root password for localhost root account.
  mysql_user:
    name: "{{ mariadb_root_username }}"
    host: "{{ item }}"
    password: "{{ mariadb_root_password }}"
    state: present
  with_items: "{{ mariadb_root_hosts.stdout_lines|default([]) }}"
  when: mariadb_root_password_update
  notify: restart mariadb


- name: root password is present
  mysql_user: name=root host={{item}} password={{mariadb_root_password | mandatory}} state=present
  with_items: "{{ mariadb_root_hosts.stdout_lines|default([]) }}"

# Has to be after the root password assignment, for idempotency.
- name: Copy .my.cnf file with root password credentials.
  template:
    src: "user-my.cnf.j2"
    dest: "{{ mariadb_user_home }}/.my.cnf"
    owner: root
    group: root
    mode: 0600

- name: Remove anonymous MariaDB users.
  mysql_user:
     name: ""
     host: "{{ item }}"
     state: absent
  with_items: "{{ mariadb_root_hosts.stdout_lines|default([]) }}"

- name: Remove MariaDB test database.
  mysql_db:
    name: test
    state: absent
