galaxy_info:
  author: Damien Lagae <damienlagae@gmail.com>
  description: MariaDB for RedHat/CentOS.
  company: []
  license: "license (BSD, MIT)"
  min_ansible_version: 1.9
  platforms:
  - name: EL
    versions:
    - 7
  galaxy_tags:
    - mariadb
    - mysql
    - database
    - web
    - development
  dependencies:
    - damienlagae.base
