---
- name: BASE | Configure os
  set_fact:
    server_base_os: "{{ansible_distribution|lower}}"

- name: BASE | Include os variables
  include_vars: "defaults/{{server_base_os}}.yml"

- name: BASE | Install package
  package: name={{item}} state=latest
  with_items:
    - "{{ base_package }}"

- include: 'repos.yml'
  when: "server_base_os == 'centos'"

- include: 'timezone.yml'
- include: 'user.yml'
