---
- name: Install SCL repository
  yum: name={{item}} state=latest update_cache=yes
  with_items:
    - scl-utils
    - centos-release-scl
    - centos-release-scl-rh

- name: Import EPEL GPG Key
  rpm_key: state=present key=https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7

- name: Install EPEL repository
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
