---
- name: Reset timezone
  file:
    path: /etc/localtime
    state: absent

- name: Set correct timezone
  file:
    src: /usr/share/zoneinfo/Europe/Brussels
    dest: /etc/localtime
    state: link